apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 191919-test

resources:
  - ../../cluster-templates/aws-ha/base
  - cluster-config.yaml

# Patches to customize the cluster
patches:
  # Update ClusterDeployment with specific values
  - target:
      kind: ClusterDeployment
    patch: |-
     - op: replace
       path: /metadata/name
       value: 191919-test
     - op: replace
       path: /metadata/namespace
       value: 191919-test
     - op: replace
       path: /spec/clusterName
       value: 191919-test
     - op: replace
       path: /spec/baseDomain
       value: openshiftpartnerlabs.com
     - op: replace
       path: /spec/platform/aws/region
       value: apac1
     - op: replace
       path: /spec/provisioning/imageSetRef/name
       value: 4.19.0
     - op: replace
       path: /spec/provisioning/installConfigSecretRef/name
       value: 191919-test-install-config
     - op: replace
       path: /spec/provisioning/sshPrivateKeySecretRef/name
       value: 191919-test-ssh-key
     - op: replace
       path: /spec/pullSecretRef/name
       value: 191919-test-pull-secret
     - op: replace
       path: /spec/platform/aws/credentialsSecretRef/name
       value: 191919-test-aws-credentials
     - op: remove
       path: /spec/provisioning/manifestsConfigMapRef

  # Update MachinePool with specific values
  - target:
      kind: MachinePool
    patch: |-
     - op: replace
       path: /metadata/name
       value: 191919-test-worker
     - op: replace
       path: /metadata/namespace
       value: 191919-test
     - op: replace
       path: /spec/clusterDeploymentRef/name
       value: 191919-test
     - op: replace
       path: /spec/platform/aws/type
       value: m5.2xlarge
     - op: replace
       path: /spec/replicas
       value: 2

  # Update ManagedCluster
  - target:
      kind: ManagedCluster
    patch: |-
     - op: replace
       path: /metadata/name
       value: 191919-test
     - op: replace
       path: /metadata/labels/environment
       value: staging

  # Update KlusterletAddonConfig
  - target:
      kind: KlusterletAddonConfig
    patch: |-
     - op: replace
       path: /metadata/name
       value: 191919-test
     - op: replace
       path: /metadata/namespace
       value: 191919-test
     - op: replace
       path: /spec/clusterName
       value: 191919-test
     - op: replace
       path: /spec/clusterNamespace
       value: 191919-test

  # Update install-config Secret
  - target:
      kind: Secret
      name: cluster-placeholder-install-config
    patch: |-
     - op: replace
       path: /metadata/name
       value: 191919-test-install-config
     - op: replace
       path: /metadata/namespace
       value: 191919-test
     - op: replace
       path: /stringData/install-config.yaml
       value: |
         apiVersion: v1
         baseDomain: openshiftpartnerlabs.com
         metadata:
           name: 191919-test

         controlPlane:
           name: master
           platform:
             aws:
               type: m5.xlarge
               rootVolume:
                 iops: 4000
                 size: 120
                 type: gp3
               zones:
                 - apac1a
           replicas: 3

         compute:
           - name: worker
             platform:
               aws:
                 type: m5.2xlarge
                 rootVolume:
                   iops: 2000
                   size: 100
                   type: gp3
                 zones:
                   - apac1a
                   - apac1b
                   - apac1c
             replicas: 2

         networking:
           clusterNetwork:
             - cidr: 10.128.0.0/14
               hostPrefix: 23
           machineNetwork:
             - cidr: 10.0.0.0/16
           serviceNetwork:
             - 172.30.0.0/16
           networkType: OVNKubernetes

         platform:
           aws:
             region: apac1

         fips: false
         publish: External

# Hive will automatically populate clusterMetadata fields after provisioning
